import { StateType } from "./Types";

export const initialState: StateType = {
  count: 0,
  clickMenu: false,
  personalDataCustomer: false,
  name: '',
  quantity: 0,
  codOriginal: '',
  codeOriginalId: 0,
  codProducer: '',
  producer: '',
  producerId: 0,
  description: '',
  vehicle: '',
  brand: '',
  model: '',
  costPrice: 0,
  salePrice: 0,
  category: '',
  ncm: 0,
  image: '',
  models: [],
  registerModels: true,
};
